name: Run UI tests

on: workflow_call

jobs:
  checkstyle:
    uses: ./.github/workflows/checkstyle-validation.yml

  run-ui-tests:
    needs: checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Teamcity setup
        uses: ./.github/actions/teamcity-setup

      - name: Run UI tests
        # Указываем группу, чтобы еще раз не запустить тесты, которые использовались для сетапа сервера и агента
        run: ./mvnw test -Dtest='com.teamcity.ui.**' -Dgroups=Regression

      # Следующие 3 степа на сохранение Allure репортов с историей и публикацию их в GitHub Pages.
      # Необходимо ознакомиться с документацией: https://allurereport.org/docs/integrations-github/,
      # так как есть степы, которые необходимо выполнить вручную в настройках репозитория, чтобы публикация работала корректно.
      # Рекомендованные степы для создания пустой ветки gh-pages, используемой для публикации репортов: https://gist.github.com/ramnathv/2227408?permalink_comment_id=2915143#gistcomment-2915143
      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results
          subfolder: ui

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Override page url
        run: echo "new_page_url=${{ steps.deployment.outputs.page_url }}ui/" >> $GITHUB_OUTPUT
