name: Deploy backend

on: workflow_call

# Это лишь примерные степы, как может выглядеть пайплайн бэкенда
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build backend
        run: echo Собирается билд бэкенда \(при сборке прогоняются юнит тесты\), формируется и публикуется Docker образ

  deploy-stage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy backend to stage
        run: echo Происходит деплой бэкенда на стейдж
