name: Deploy frontend

on: workflow_call

# Деплой бэкенда и фронтенда на прод
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy backend to production
        run: echo Происходит деплой бэкенда на прод

  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy backend to production
        run: echo Происходит деплой фронтенда на прод
