name: Deploy frontend

on: workflow_call

# Это лишь примерные степы, как может выглядеть пайплайн фронтенда
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test frontend
        run: echo Запускаются юнит тесты и линтеры фронтенда, формируется и публикуется Docker образ

  deploy-stage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to stage
        run: echo Происходит деплой фронтенда на стейдж
