name: TeamCity deployment

on: push

jobs:
  # Собирается бэкенд и деплоится на стейдж
  backend:
    uses: ./.github/workflows/backend-stage.yml

  # Собирается фронтенд и деплоится на стейдж
  frontend:
    uses: ./.github/workflows/frontend-stage.yml

  # Прогоняются автотесты на стейдже
  automation-api:
    needs: [ backend, frontend ]
    uses: ./.github/workflows/automation-api.yml

  # Прогоняются автотесты на стейдже
  automation-ui:
    needs: [ backend, frontend ]
    uses: ./.github/workflows/automation-ui.yml

  allure-publish:
    needs: [ automation-api, automation-ui ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: $
          publish_branch: gh-pages
          publish_dir: allure-history

  # Необходим мануальный апрув, чтобы задеплоить бэкенд и фронтенд на прод
  # Нужно настроить prod environment. Инструкция: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#creating-an-environment
  # При желании, можно убрать этот шаг, чтобы деплой на прод начинался автоматически, если прошли все автотесты
  # Однако, мануальное действие здесь поможет провести дополнительное ревью, а также, например, какие-то мануальные или перформанс тесты,
  # так как деплой на прод - это очень серьезное действие
  manual-prod-approval:
    environment: 'prod'
    runs-on: ubuntu-latest
    needs: allure-publish
    steps:
      - name: Approve backend and frontend to production
        run: echo Approved to production

  # Деплой бэкенда и фронтенда на прод
  deploy-prod:
    needs: manual-prod-approval
    uses: ./.github/workflows/deploy-prod.yml
