name: TeamCity deployment

on: [ push, workflow_dispatch ]

jobs:
  # Собирается бэкенд и деплоится на стейдж
  backend:
    uses: ./.github/workflows/backend-stage.yml

  # Собирается фронтенд и деплоится на стейдж
  frontend:
    uses: ./.github/workflows/frontend-stage.yml

  # Прогоняются API автотесты
  automation-api:
    needs: [ backend, frontend ]
    uses: ./.github/workflows/automation.yml
    with:
      package: api

  # Прогоняются UI автотесты
  automation-ui:
    needs: [ backend, frontend ]
    uses: ./.github/workflows/automation.yml
    with:
      package: ui

  automation-ui-firefox:
    needs: [ backend, frontend ]
    uses: ./.github/workflows/automation.yml
    with:
      package: ui
      browser: firefox

  report:
    needs: [ automation-api, automation-ui, automation-ui-firefox ]
    if: always()
    uses: ./.github/workflows/report.yml

  # Необходим мануальный апрув, чтобы задеплоить бэкенд и фронтенд на прод
  # Нужно настроить prod environment. Инструкция: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#creating-an-environment
  # При желании, можно убрать этот шаг, чтобы деплой на прод начинался автоматически, если прошли все автотесты
  # Однако, мануальное действие здесь поможет провести дополнительное ревью, а также, например, какие-то мануальные или перформанс тесты,
  # так как деплой на прод - это очень серьезное действие
  manual-prod-approval:
    needs: report
    if: success()
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Approve backend and frontend to production
        run: echo Approved to production

  # Деплой бэкенда и фронтенда на прод
  deploy-prod:
    needs: manual-prod-approval
    uses: ./.github/workflows/deploy-prod.yml
