name: Allure report

on: workflow_call

jobs:
  allure-report:
    runs-on: ubuntu-latest
    steps:
      # Выкачиваем все артефакты в одну директорию для формирования одного общего репорта
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: allure-results
          merge-multiple: true

      # Следующие 3 степа на сохранение Allure репортов с историей и публикацию их в GitHub Pages.
      # Необходимо ознакомиться с документацией: https://allurereport.org/docs/integrations-github/,
      # так как есть степы, которые необходимо выполнить вручную в настройках репозитория, чтобы публикация работала корректно.
      # Рекомендованные степы для создания пустой ветки gh-pages, используемой для публикации репортов: https://gist.github.com/ramnathv/2227408?permalink_comment_id=2915143#gistcomment-2915143
      - name: Load test report history
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.9
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
