name: TeamCity tests

on: push

jobs:
  run_teamcity_server:
    runs-on: ubuntu-latest
    steps:
      - name: prepare environment
        run: |
          echo "Current IP address is $(curl -s ifconfig.me)"
          mkdir teamcity_server
          sudo chown -R 1000:1000 teamcity_server
          cd teamcity_server
      - name: run teamcity server
        run: docker run --name teamcity-server-instance \
          -v $(pwd)/datadir:/data/teamcity_server/datadir \
          -v $(pwd)/logs:/opt/teamcity/logs \
          -p 8111:8111 jetbrains/teamcity-server
