name: TeamCity tests

on: push

jobs:
  run_teamcity_server:
    runs-on: ubuntu-latest
    steps:
      - name: prepare environment
        run: |
          echo "Current IP address is $(curl -s ifconfig.me)"
          mkdir teamcity_server
          sudo chown -R 1000:1000 teamcity_server
          echo $(pwd)
          ls
          cd ..
          echo $(pwd)
          ls
          cd /
          echo $(pwd)
          ls
          cd /tmp
          echo $(pwd)
          ls

